prova pubblicazione pt2

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -9,10 +9,10 @@ jobs:
   build-and-deploy:
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout repository
+      - name: Checkout
         uses: actions/checkout@v3
 
-      - name: Setup Node.js environment
+      - name: Setup Node.js
         uses: actions/setup-node@v3
         with:
           node-version: 18
@@ -20,14 +20,20 @@ jobs:
       - name: Install dependencies
         run: npm ci
 
-      - name: Build project
+      - name: Build
         run: npm run build
 
       - name: Create .nojekyll file
-        run: touch ./build/.nojekyll
+        run: |
+          if [ -d "./dist" ]; then
+            touch ./dist/.nojekyll
+          else
+            echo "Build folder not found!"
+            exit 1
+          fi
 
-      - name: Deploy to GitHub Pages
+      - name: Deploy
         uses: JamesIves/github-pages-deploy-action@v4
         with:
-          branch: gh-pages       # branch where to deploy
-          folder: build          # folder created by 'npm run build'
+          branch: gh-pages
+          folder: dist
